# Generated by Django 5.1.4 on 2025-05-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseReports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reportid', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('station', models.CharField(blank=True, max_length=20, null=True)),
                ('suspects', models.CharField(blank=True, max_length=20, null=True)),
                ('culprit', models.CharField(blank=True, max_length=20, null=True)),
                ('casedescription', models.CharField(blank=True, max_length=1000, null=True)),
                ('officer', models.CharField(blank=True, max_length=20, null=True)),
                ('chiefofficer', models.CharField(blank=True, max_length=20, null=True)),
                ('reportdate', models.DateTimeField(auto_now_add=True)),
                ('confirm', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'CaseReports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvidentImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='evidence/images/')),
            ],
            options={
                'db_table': 'EvidentImages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvidentVideos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video', models.FileField(blank=True, null=True, upload_to='evidence/videos/')),
            ],
            options={
                'db_table': 'EvidentVideos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.CharField(blank=True, max_length=900, null=True)),
            ],
            options={
                'db_table': 'FeedBack',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RankChangeRequests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('policeid', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('station', models.CharField(blank=True, max_length=20, null=True)),
                ('currentrank', models.CharField(blank=True, max_length=20, null=True)),
                ('updaterank', models.CharField(blank=True, max_length=20, null=True)),
                ('confirmation', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'RankChangeRequests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regionname', models.CharField(blank=True, max_length=50, null=True)),
                ('crimetype', models.CharField(blank=True, max_length=50, null=True)),
                ('reportdate', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('assignedpoliceid', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('casedate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Reports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('policeid', models.IntegerField(blank=True, null=True)),
                ('rank', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('station', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegionChangeRequests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('policeid', models.IntegerField(blank=True, null=True)),
                ('rank', models.CharField(blank=True, max_length=20, null=True)),
                ('currentlocation', models.CharField(blank=True, max_length=30, null=True)),
                ('updatelocation', models.CharField(blank=True, max_length=30, null=True)),
                ('confirmation', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'RegionChangeRequests',
                'managed': True,
            },
        ),
    ]
