# Generated by Django 5.2.8 on 2025-12-03 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regionchangerequests',
            options={'managed': False},
        ),
    ]
